name: Git Conventions

on:
  workflow_call:
    inputs:
      runs_on:
        description: 'Runner OS to use'
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check conventional commits
        uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69 # v1.4.2
