name: Git Conventions

on:
  workflow_call:
    inputs:
      runs_on:
        description: 'Runner OS to use'
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Check conventional commits
        uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69 # v1.4.2
