name: Helm Lint

on:
  workflow_call:
    inputs:
      chart_path:
        description: 'Path to the Helm chart directory (e.g. charts/my-chart)'
        required: true
        type: string
      helm_version:
        description: 'Helm version to install'
        required: false
        type: string
        default: 'latest'
      runs_on:
        description: 'Runner OS to use'
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  lint:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
        with:
          version: ${{ inputs.helm_version }}

      - name: Run Helm lint
        run: helm lint ${{ inputs.chart_path }}
