name: MkDocs Deploy

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.x'
      runs_on:
        description: 'Runner OS to use'
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  deploy:
    runs-on: ${{ inputs.runs_on }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ inputs.python_version }}

      - name: Set cache ID
        id: cache-id
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_OUTPUT

      - name: Cache mkdocs-material
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: mkdocs-material-${{ steps.cache-id.outputs.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install mkdocs-material
        run: pip install mkdocs-material

      - name: Deploy docs
        run: mkdocs gh-deploy --force
